package Modelo;
// Generated 23/10/2018 12:07:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private Integer idcurso;
     private Profesor profesor;
     private String nombre;
     private String duracion;
     private String horas;
     private String aula;
     private String cupo;
     private int idtematica;
     private Set inscripcions = new HashSet(0);

    public Curso() {
    }

	
    public Curso(Profesor profesor, int idtematica) {
        this.profesor = profesor;
        this.idtematica = idtematica;
    }
    public Curso(Profesor profesor, String nombre, String duracion, String horas, String aula, String cupo, int idtematica, Set inscripcions) {
       this.profesor = profesor;
       this.nombre = nombre;
       this.duracion = duracion;
       this.horas = horas;
       this.aula = aula;
       this.cupo = cupo;
       this.idtematica = idtematica;
       this.inscripcions = inscripcions;
    }
   
    public Integer getIdcurso() {
        return this.idcurso;
    }
    
    public void setIdcurso(Integer idcurso) {
        this.idcurso = idcurso;
    }
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(String duracion) {
        this.duracion = duracion;
    }
    public String getHoras() {
        return this.horas;
    }
    
    public void setHoras(String horas) {
        this.horas = horas;
    }
    public String getAula() {
        return this.aula;
    }
    
    public void setAula(String aula) {
        this.aula = aula;
    }
    public String getCupo() {
        return this.cupo;
    }
    
    public void setCupo(String cupo) {
        this.cupo = cupo;
    }
    public int getIdtematica() {
        return this.idtematica;
    }
    
    public void setIdtematica(int idtematica) {
        this.idtematica = idtematica;
    }
    public Set getInscripcions() {
        return this.inscripcions;
    }
    
    public void setInscripcions(Set inscripcions) {
        this.inscripcions = inscripcions;
    }




}


