package Modelo;
// Generated 23/10/2018 12:07:25 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Participante generated by hbm2java
 */
public class Participante  implements java.io.Serializable {


     private Integer idparticipante;
     private String apellido;
     private String nombre;
     private Date fechan;
     private String tutor;
     private String tel;
     private String dire;
     private String email;
     private Set inscripcions = new HashSet(0);

    public Participante() {
    }

    public Participante(String apellido, String nombre, Date fechan, String tutor, String tel, String dire, String email, Set inscripcions) {
       this.apellido = apellido;
       this.nombre = nombre;
       this.fechan = fechan;
       this.tutor = tutor;
       this.tel = tel;
       this.dire = dire;
       this.email = email;
       this.inscripcions = inscripcions;
    }
   
    public Integer getIdparticipante() {
        return this.idparticipante;
    }
    
    public void setIdparticipante(Integer idparticipante) {
        this.idparticipante = idparticipante;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechan() {
        return this.fechan;
    }
    
    public void setFechan(Date fechan) {
        this.fechan = fechan;
    }
    public String getTutor() {
        return this.tutor;
    }
    
    public void setTutor(String tutor) {
        this.tutor = tutor;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getDire() {
        return this.dire;
    }
    
    public void setDire(String dire) {
        this.dire = dire;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getInscripcions() {
        return this.inscripcions;
    }
    
    public void setInscripcions(Set inscripcions) {
        this.inscripcions = inscripcions;
    }




}


