package Modelo;
// Generated 23/10/2018 12:07:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Profesor generated by hbm2java
 */
public class Profesor  implements java.io.Serializable {


     private Integer idprofesor;
     private String nombre;
     private Set cursos = new HashSet(0);

    public Profesor() {
    }

    public Profesor(String nombre, Set cursos) {
       this.nombre = nombre;
       this.cursos = cursos;
    }
   
    public Integer getIdprofesor() {
        return this.idprofesor;
    }
    
    public void setIdprofesor(Integer idprofesor) {
        this.idprofesor = idprofesor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set cursos) {
        this.cursos = cursos;
    }




}


